### ISSUE TITLE
ExternalTextProcessor: Pretend to care about efficiency

### ISSUE THREAD

**Issue by kpu** [bitextor/bitextor#163] opened 2020-03-01 16:00 UTC
So far as I can tell https://github.com/bitextor/bitextor/blob/master/bitextor-tokenize.py and https://github.com/bitextor/bitextor/blob/master/bitextor-tokenize-moses.py launch new processes for every document.  That's really inefficient.  

I constructed an admittedly-difficult case with some short Lithuanian lines from CommonCrawl.  
```bash
xzcat /fs/dagr0/heafield/ccwmt/lt.deduped.xz |head -n 5000 >foo.txt
```

Here's the raw tokenizer:
```bash
time /fs/snotra0/heafield/preprocess/moses/tokenizer/tokenizer.perl -l lt >/dev/null <foo.txt
real    0m0.217s
user    0m0.216s
sys     0m0.000s
```

And this python program that simplifies https://github.com/bitextor/bitextor/blob/master/bitextor-tokenize-moses.py :
```python
#!/usr/bin/env python3
import sys
sys.path.append("/fs/snotra0/heafield/bitextor/")
from external_processor import ExternalTextProcessor

for line in sys.stdin:
  proc = ExternalTextProcessor("/fs/snotra0/heafield/preprocess/moses/tokenizer/tokenizer.perl -l en -b".split())
  text = proc.process(line)
  sys.stdout.write(text)
```

```bash
time ./above.py <foo.txt >/dev/null
real    3m40.036s
user    3m13.376s
sys     0m20.700s
```

This is admittedly an extreme case with short lines.  The tokenizer is one line in one line out.  Use that and do a buffered pattern rather than a one-in-one-out pattern.  And we should also modify the sentence splitter where necessary to have some notion of document records.

**Comment by lpla** [comment] 2020-03-02 10:20
We are aware of this issue and it is implemented in the branch 'new_tokenizer', which implements both sentence splitter and word tokenizer efficiently by default (Moses ones). The only issue for Paracrawl production is that this is implemented on top of the branch "formatchanges", so if you are using master branch code, using this 'new_tokenizer' branch will probably break some already running workflows.

If you are using 'formatchanges' branch, you can use this code quite safely, but keep in mind we are still testing it for any regression. This is planned for the next Bitextor release (8.0).

The reason both sentence splitter and word tokenizer were called from "ExternalTextProcessor" (one call for every document/line) was to provide better compatibility for these user provided tools.

Concretely, some time ago (https://github.com/bitextor/bitextor/commit/3ac8bce9d2e39516b2e718693d687f5b49421685) we had 'ToolWrapper' calls for word tokenizer, but it had several issues with some tokenizers that had output buffering, so we decided to move forward to 'ExternalTextProcessor' in that commit.

**Comment by lpla** [comment] 2020-03-06 15:06
We just merged 'new_tokenizer' branch in master through #167 .

**Closed by lpla** 2020-03-06 15:06 UTC
