### ISSUE TITLE
How to crawl one specific domain without jumping to others.

### ISSUE THREAD

**Issue by vince62s** [bitextor/bitextor#115] opened 2019-07-01 09:56 UTC
I am trying this tool fighting with yaml examples.

httrack: true

How can I crawl a single website without letting httrack crawling all external links (facebook, ....)
Thanks

**Comment by lpla** [comment] 2019-07-01 09:59
Crawlers are configured to only crawl in-domain documents. If one gets out of the domain it is a bug in that concrete crawler or a redirect that is not well managed. Please, try with other crawlers (`wget` and `creepy`): https://github.com/bitextor/bitextor#variables-for-crawling-configuration

**Comment by vince62s** [comment] 2019-07-01 10:02
okay, also,
let's assume I know that I want crawl fr and es languages and that both are mainly in
www.company.com/fr and www.company.com/es
what is the best way so that it does not lose time to crawl www.company.com/en ?
I put 2 urls in hosts ?

**Comment by lpla** [comment] 2019-07-01 10:06
We don't have any way to configure that for now. We are researching on this kind of targeted crawling. The only thing that can be done now is crawling specific URLs manually with a crawler like `wget`, which has WARC conversion built in, and replace the *.warc.xz file generated by Bitextor with the one that `wget` created.

**Comment by vince62s** [comment] 2019-07-01 10:09
switching to creepy requires installation of warc
and then in Python3 import __builtin__ does not work because this is Python2 ...
in 3 it needs __builtins__
so is this Python3 or 2 compatible ?

**Comment by vince62s** [comment] 2019-07-01 10:20
wow not even close: https://github.com/internetarchive/warc/pull/26
do you guys use a in-house warc version ?

**Comment by lpla** [comment] 2019-07-01 11:04
We use [`warcio`](https://github.com/webrecorder/warcio). Please, check installation instructions (dependencies and submodules installation): https://github.com/bitextor/bitextor#dependencies

**Comment by vince62s** [comment] 2019-07-01 12:54
I did follow exactly the instructions and I see warcio in pip list.
BUT when switching to "crawler: creepy"
Traceback (most recent call last):
  File "./bitextor-creepy.py", line 33, in <module>
    import warc
ModuleNotFoundError: No module named 'warc'

**Comment by lpla** [comment] 2019-07-01 13:29
Oh, I see. We are still using `warc3-wet` library for some cases. I will add it again to dependencies and release a bugfix version. Please, try after installing `pip install warc3-wet`

**Comment by vince62s** [comment] 2019-07-01 13:36
ok another error:
When in HTtrack mode if it does not find the .dic file from this line "dic: ~/permanent/fr-es.dic"
then it builds the dic from the initCorpusTrainPrefix as mentioned in the doc,
in creepy mode:
FileNotFoundError: [Errno 2] No such file or directory: '/home/moses/permanent/fr-es.dic'
Command exited with non-zero status 1

**Comment by lpla** [comment] 2019-07-01 14:05
Could you give me more error info? I am not able to reproduce that

**Comment by vince62s** [comment] 2019-07-01 14:15
Traceback (most recent call last):
  File "./bitextor-idx2ridx.py", line 139, in <module>
    load_dictionaries(options.dictionary, options.lang1, options.lang2, dic)
  File "./bitextor-idx2ridx.py", line 60, in load_dictionaries
    file = open(dictionary, "r")
FileNotFoundError: [Errno 2] No such file or directory: '/home/user/permanent/fr-es.dic'
Command exited with non-zero status 1
	Command being timed: "./bitextor-idx2ridx.py -d /home/user/permanent/fr-es.dic --lang1 fr --lang2 es"
	User time (seconds): 0.10
	System time (seconds): 0.00
	Percent of CPU this job got: 99%
	Elapsed (wall clock) time (h:mm:ss or m:ss): 0:00.10
	Average shared text size (kbytes): 0
	Average unshared data size (kbytes): 0
	Average stack size (kbytes): 0
	Average total size (kbytes): 0
	Maximum resident set size (kbytes): 24784
	Average resident set size (kbytes): 0
	Major (requiring I/O) page faults: 0
	Minor (reclaiming a frame) page faults: 3552
	Voluntary context switches: 1
	Involuntary context switches: 3
	Swaps: 0
	File system inputs: 0
	File system outputs: 0
	Socket messages sent: 0
	Socket messages received: 0
	Signals delivered: 0
	Page size (bytes): 4096
	Exit status: 1
[Mon Jul  1 16:10:20 2019]
Error in rule idx2ridx_l1tol2:
    jobid: 40
    output: /home/user/transient-default-fr-es/samsung/1.ridx.xz

RuleException:
CalledProcessError in line 1058 of /home/user/bitextor/snakemake/Snakefile:
Command 'set -euo pipefail;  xzcat -T 0 -f /home/user/transient-default-fr-es/samsung/idx.xz | /usr/bin/time -v ./bitextor-idx2ridx.py -d /home/user/permanent/fr-es.dic --lang1 fr --lang2 es | xz -T 0 > /home/user/transient-default-fr-es/samsung/1.ridx.xz' returned non-zero exit status 1.
  File "/home/user/bitextor/snakemake/Snakefile", line 1058, in __rule_idx2ridx_l1tol2
  File "/usr/lib/python3.6/concurrent/futures/thread.py", line 56, in run



The config file is as follow:
bitextor: ~/permanent/bitextor
hosts: ["www.samsung.com"]
crawler: creepy
crawlTld: false
crawlerNumThreads: 8
permanentDir: ~/permanent/bitextor-output-samsung-fr-es
transientDir: ~/transient-default-fr-es
LANG1Tokenizer: ~/bitextor/preprocess/moses/tokenizer/tokenizer.perl -q -b -a -l fr
LANG2Tokenizer: ~/bitextor/preprocess/moses/tokenizer/tokenizer.perl -q -b -a -l es
temp: ~/transient-default-fr-es
lang1: fr
lang2: es
dic: ~/permanent/fr-es.dic
hunalignThreshold: 0
elrc: true
documentAligner: DIC
#bicleaner: ~/bicleaner-model/fr-es/training.fr-es.yaml
initCorpusTrainPrefix: ["/home/user/bitextor/Europarl.es-fr.clean"]
tmx: true
profiling: true

**Comment by lpla** [comment] 2019-07-02 11:03
Could you try latest commit from master? Doing `git pull` in `bitextor` folder should do the work.

**Comment by lpla** [comment] 2019-07-12 10:04
Did it work?

**Comment by vince62s** [comment] 2019-07-12 10:10
I'm sorry I didn't get a chance to try. In the meantime I used httrack crawler with some other settings to avoid crawling outside the target domain, but it still takes for ever.
Without any prefiltering based on languages (for instance www.domain.com/es + www.domain.com/en or any other trick) it unusable in a timely manner.

**Comment by lpla** [comment] 2019-07-12 10:18
I know that there are some cases of huge sites that are not able to be crawled given the time constrain. As I said:

> We don't have any way to configure that for now. We are researching on this kind of targeted crawling. The only thing that can be done now is crawling specific URLs manually with a crawler like `wget`, which has WARC conversion built in, and replace the *.warc.xz file generated by Bitextor with the one that `wget` created.

I will keep this issue open for any implementation idea that comes up to anyone, or implementation details.

**Comment by vince62s** [comment] 2019-07-12 12:17
here https://github.com/bitextor/bitextor/blob/master/bitextor-httrack.py#L54
removing extended-parsing helps.

**Comment by lpla** [comment] 2019-08-27 09:04
Thank you! We implemented that in https://github.com/bitextor/bitextor/commit/d218d66cee52da2772190ca857eb30778b61f902

Closing the issue now

**Closed by lpla** 2019-08-27 09:04 UTC
Labels: enhancement
