### ISSUE TITLE
warc2preprocess writes images to output directory

### ISSUE THREAD

**Issue by wwaites** [bitextor/bitextor#113] opened 2019-06-21 08:39 UTC
I do not know why, and quite possibly this will be fixed when warc2preprocess checks that input is some kind of text (#112) but right now when given an Internet Archive WARC file it writes zillions of images to the output directory. This is unhelpful and may have an adverse effect on performance.

**Comment by lpla** [comment] 2019-06-21 10:18
You are right. We check file format in crawlers but not in warc2preprocess. I will add a filter for supported formats (HTML, XML, PDF, OpenDocuments, ePub) as soon as possible (probably Wednesday, holidays in UAlicante until then).

**Comment by lpla** [comment] 2019-06-26 09:54
Hi, I'm back. Could you tell me the name of the Internet Archive WARC you used for your tests and stats? The one I am using doesn't have image, PDFs or other kind of undesired WARC entries.

**Comment by wwaites** [comment] 2019-06-26 10:05
SURV-20141218203026-00019.warc.gz

**Comment by lpla** [comment] 2019-06-27 09:29
Well, this is a side issue. It was caused by `pdftohtml` call, which writes in disk all the images it detects in a PDF. I added an option to ignore images: https://github.com/bitextor/bitextor/commit/40874e714dab201c8779453da2350b51c2ab3421

If you get any issue like this one, please don't hesitate to tell me.

Closing

**Closed by lpla** 2019-06-27 09:29 UTC
