### ISSUE TITLE
Arabic Text is garbled and concatenated 

### ISSUE THREAD

**Issue by mzeidhassan** [bitextor/bitextor#67] opened 2018-12-28 06:10 UTC
Hi Bitextor team,
I am using the latest release and I noticed that Arabic text is now concatenated and glued to each other. Not sure why, but I didn't have such issue in earlier releases. Any idea? Please see screen shot to see what I mean. 

Thanks!

![image](https://user-images.githubusercontent.com/7589948/50504676-80f6af80-0a2c-11e9-8f1a-37297baf4ff4.png)

**Comment by mespla** [comment] 2018-12-28 09:17
Hi, can you provide some more details? Which website are you trying to crawl? Which options are you using to run Bitextor? I will try to reproduce the problem.

**Comment by mzeidhassan** [comment] 2018-12-28 23:07
Hi @mespla ,

I was just testing it with a random en-ar site to see. Here is the command I used:

`bitextor -u http://www.nestle-family.com/recipes/english/al-rashoof_45625.aspx -v /home/Documents/bitextor/en-ar.dic -L /home/Documents/nestle/log -I /home/Documents/Bitextor_output/nestle -t 10m -O /home/Documents/nestle.tmx -b 1 -x en ar`

The most important thing now is to find a fix for the garbled text. 
Thanks for your support!

**Comment by lpla** [comment] 2019-01-02 19:56
Hello @mzeidhassan. Could you share the en-ar.dic you used to try to reproduce the same output as you?

Also, for the "actual recipe" issue, for now Bitextor crawls a whole domain, not a single page, even if you specify it using `-u` parameter. That means that the text result is going to be the same if you use `http://www.nestle-family.com/recipes/english/al-rashoof_45625.aspx` or simply `http://www.nestle-family.com`, because that 'strip' is what our crawler does and uses to start crawling from.

**Comment by lpla** [comment] 2019-01-17 10:47
I am unable to reproduce the problem. I crawled the same domain (24 hours and I stopped the process), and the result has correctly separated words, using spaces. I am reading the output file with `less` and `vim`. Maybe it is related with your TMX/tab separated files reader. Which are you using @mzeidhassan ? Looks like Libreoffice Calc or similar.

**Comment by lpla** [comment] 2019-01-17 11:11
Just one more thing. Could you try to run the same command line adding `-B` option? I suspect this is the root of the issue.

**Comment by mzeidhassan** [comment] 2019-01-21 07:03
> I am unable to reproduce the problem. I crawled the same domain (24 hours and I stopped the process), and the result has correctly separated words, using spaces. I am reading the output file with `less` and `vim`. 
> 
Can you share the output file here, a screen shot will do? I will try the -B option and get back to you?

**Comment by lpla** [comment] 2019-01-21 08:21
> > I am unable to reproduce the problem. I crawled the same domain (24 hours and I stopped the process), and the result has correctly separated words, using spaces. I am reading the output file with `less` and `vim`.
> 
> @lpla Can you share the output file here, a screen shot will do? I will try the -B option and get back to you?

Yes, sure

 
<img width="1680" alt="captura de pantalla 2019-01-21 a las 9 20 30" src="https://user-images.githubusercontent.com/1533393/51461280-ed2faf00-1d5d-11e9-88c1-a9d49a60fc10.png">

**Comment by mzeidhassan** [comment] 2019-01-22 02:44
Thanks @lpla for posting the image. The Arabic text shown doesn't look right. Can you upload a small text file to open it at my end and see if it will open correctly on my machine with the right Arabic support? What I see in the picture is not correctly rendered Arabic.

**Comment by mzeidhassan** [comment] 2019-01-23 03:49
Thank you so much @lpla ! I confirm that Arabic is displayed correctly in your TMX file. OK, I will test the -B option. Can you please let me know what is the exact command you used at your end? Thanks again!

One last thing:

For some reason, the generated TMX file doesn't open in some TMX editors unless I open it and add change:

<?xml version="1.0"?>

to

<?xml version="1.0" encoding="utf-8"?>

The other thing is that some editors complained about the data format

`=================================== Start Process
--- 23-Jan-2019 05:47:57 ---------- Start Task
Opening TM...
Warning: The value '20190117T124124' is an invalid date. The current date/time will be used instead. 
Number of entries read = 234 (Added = 234)
Duration = 00:00:00.3257877
--- 23-Jan-2019 05:47:58 ---------- End Task
Warning count = 1
=================================== End Process
`

**Comment by lpla** [comment] 2019-01-23 07:42
`bitextor -u http://www.nestle-family.com/ -v bitextor-dictionaries/en-ar.dic -x -T tmp/ -L testinglog5 -I testinginterm5 en ar > nestle2.tmx`

`-u` is the url, `-v` is the dictionary file, `-x` is to output in TMX format, `-T` is to write in my `home` temporary folder instead of system (because of small size of `/`), `-L` to keep logs folder and `-I` to keep the intermediate files folder.

**Comment by mzeidhassan** [comment] 2019-01-23 15:14
Thank you so much @lpla for your help. I tested the -B option yesterday and it seems to be working fine. Without it, the Arabic text is garbled at my end for some reason. 

You said above that you left it running for 24 hours. When I use this command or even my own command, it stops after about 2 minutes. It does create a tmx file with 226 segments, but it seems it doesn't go through all pages in the site, even if I use the -t flag and set it to 1440m which is basically a day. Any idea why this is happening? How many segments are there in the file you created after 24 hours? Thanks again for your support.

**Comment by lpla** [comment] 2019-01-23 21:52
Try doing a “git pull” to receive the latest changes I made in master branch. I added a fix for utf-8 encoded urls earlier this week.

**Comment by mzeidhassan** [comment] 2019-01-24 21:43
Hi @lpla, I updated Bitextor, but still the number of extracted pairs are very low. Not sure what is the reason. Can you confirm how many pairs did you get when you ran the command for 24 hours?

**Comment by lpla** [comment] 2019-01-25 12:31
The nestle2.tmx file I uploaded is the result of running Bitextor after crawling for a day. Take into account that the default Bitextor crawler (Creepy) takes different random paths in every run, so if you stop the crawling (our case), the mirrored content would be different in each run. And in the worst case, if you only downloaded content in one language in this "path", there won't be any parallel data to pair.

**Comment by lpla** [comment] 2019-01-29 10:48
I think that, usually, user doesn't know all pages/documents/URLs that contain data that is translated on/from another one, even a small set of them.

Random path is a feature from Creepy crawler, but you could use the crawler you want if you create ETT files from the crawled output. In fact, we also support HTTrack as an alternative because it is more standard, but sometimes less flexible. And both crawlers download a whole domain, if you don't stop it earlier, as we did in the tests we performed for this issue.

As I said, those supported crawlers work for general purposes in which crawl step is not stopped and you want to obtain as much documents as possible from a domain. So, for now, if you want to work with only specific web pages/documents, you need to do it manually.

To create a ETT file from crawled content, just take a look at the format in our Wiki page: https://github.com/bitextor/bitextor/wiki/Intermediate-formats-used-in-Bitextor

We will take your proposal into account when releasing Bitextor 7.0, as it is a major redesign of the code.

If you want to discuss this further, open a new issue with this topic.

**Comment by mzeidhassan** [comment] 2019-01-30 06:03
@lpla The ETT file is not clear to me. Does Bitextor create this file? If yes, what is the command to use Creepy? I see that there is an HTTrack flag "-H". Would this flag create the ETT file? Or do I need to create the file manually? How can I use Creepy instead if I wish? I only managed to use httrack theoretically. 

I have been testing Bitextor on other websites with too many pages and it doesn't seem to extract significant pairs at all. 

I also tried to download with bitextor-downloadweb, but the directory was empty after bitextor finished the process. 

bitextor-crawl seems to work in the terminal, but I couldn't find a way to save the crawled pages to ETT or to a directory. 

I would be grateful if can shed some light on how to really use ETT. 

Thanks again for your support!

**Comment by lpla** [comment] 2019-03-11 12:03
Initial issue is fixed in commit https://github.com/bitextor/bitextor/commit/1807daf89fd7f82ca676648a251222f25cd9b0de

Code available in master and next release this week.

Please, use this new code instead of release 6.0. And, for further questions, open new issues.

Closing

**Closed by lpla** 2019-03-11 12:03 UTC
Labels: bug, unable to reproduce
