### ISSUE TITLE
warc2preprocess inefficiency

### ISSUE THREAD

**Issue by hieuhoang** [bitextor/bitextor#95] opened 2019-05-10 11:34 UTC
some warc files take weeks to process, eg. the following file has been processing for 8 days now
   http://statmt.org/hieu/paracrawl/httrack.warc.xz
It's not particularly large (27MB, 55625 pages). Just wondering if you can figure out where the inefficiency is

**Comment by lpla** [comment] 2019-05-10 15:23
Which lang pair? To reproduce it

**Comment by hieuhoang** [comment] 2019-05-10 15:36
pl-de. My guess is its a specific page

**Comment by lpla** [comment] 2019-05-13 09:04
That's weird. I run `bitextor-warc2preprocess.py` from `master` branch with this WARC file and that lang pair and took 5 hours and a half. I am trying to save time by omitting some HTML cleaning steps, without compromising alignments, and I reduced this preprocess to 4 hours. I am still evaluating this result with document aligner.

But, anyway, I am not getting those 8 days of processing with this WARC. And I am using my desktop for computing (a simple i5 processor with a slow HDD disk).

**Comment by hieuhoang** [comment] 2019-05-13 10:46
weird indeed. I tried it on my laptop and get the same results as you. There may be some interaction/memory swapping due to other processes.

However this warc definitely doesn't run even on my laptop
   http://statmt.org/hieu/paracrawl/maitresse-diane.warc.xz
fr-en, this is the command i tried
   xzcat $input -f | $BITEXTOR/bitextor-warc2preprocess.py --output-dir out --lang1 fr --lang2 en

**Comment by lpla** [comment] 2019-05-13 13:23
Well, there's a document that begins at line 15855 of that WARC and ends at line 23574233. Header shows that this document Content-length is 1784547321 (1,78 GB). Also, this huge document is also not well formed, as it looks like an error output with some html style tags.

More specifically, the lxml.clean.Cleaner call we do in warc2preprocess is why processing this document is taking so long. If I run it without lxml Cleaner, it finishes in 30 minutes. I am still working on this, but maybe the solution is a size limit for a WARC document: if we see that application/http header has a Content-length higher than X MB just ignore it.

**Comment by hieuhoang** [comment] 2019-05-14 11:03
Gonna skip pages over 5MB. Lets see if that works
  https://github.com/bitextor/bitextor/commit/8d84f4da552e8af93f3e185cefa19f823399a800

**Comment by lpla** [comment] 2019-05-14 11:22
I think you left some leftover variable `num` there.

When we add PDFtoXML support, we should specify thresholds depending on the document type (WARC value "Content-Type"), but for now this should work.

**Comment by hieuhoang** [comment] 2019-05-14 13:21
I agree, didn't think of that

btw, the logging.info() doesn't seem to output anything so I used print instead. Maybe we should use sys.stderr.write instead, or config logging to output to stderr

**Comment by lpla** [comment] 2019-05-14 13:37
`logging` only prints to stderr if you use `--verbose`  in `bitextor-warc2preprocess.py`. It works for me.

**Comment by hieuhoang** [comment] 2019-05-14 13:51
ah ok. shall we add that to the Snakefile?

**Comment by lpla** [comment] 2019-05-14 14:15
If we do, at least with an optional "verbose" option in Snakemake config file. Just in case you expect WARC containing lots of documents, because printing logs then can be a bit wild.

I could do this if you want.

**Comment by hieuhoang** [comment] 2019-05-14 14:18
let me think about it. I'll do it if I need to debug again

**Comment by hieuhoang** [comment] 2019-05-15 12:28
i'm pushing another filtering tweak to get rid of pages with unknown URLs. 
   https://github.com/bitextor/bitextor/commit/6cb8e24560b82a334763a080cca6aab075adbd8c
They made bleualign choke as 2 'pages' with unkown URLs were aligned

howl if you disagree with the commit

**Comment by hieuhoang** [comment] 2019-05-15 15:39
That reminds me - wget can create a warc file by itself, there's no need for bitextor-dir2warc.py which is the cause of the 'unknown' url issue.

Can we make use of this warc-creating feature?

**Comment by lpla** [comment] 2019-05-16 09:33
I am adding an boolean option "wget-warc" to Snakefile, which skips the generic dir2warc process and just writes WARC file from wget. I will refer this issue when I finish.

**Comment by hieuhoang** [comment] 2019-05-16 09:54
thanks. I don't think the dir2warc is generic, it parses for httrack-specific output
   https://github.com/bitextor/bitextor/blob/6cb8e24560b82a334763a080cca6aab075adbd8c/bitextor-dir2warc.py#L27

**Comment by lpla** [comment] 2019-05-16 10:09
Yep, totally right. I will made mandatory `wget` WARC output instead of dir2warc one, so dir2warc is only used in httrack.

**Comment by lpla** [comment] 2019-05-16 10:28
Done. I also updated submodules and merged all changes between `master` and `bitextor-malign`. Remember to download updated submodules with `git submodule update --recursive --remote`

**Comment by hieuhoang** [comment] 2019-05-16 11:18
cheers

**Comment by lpla** [comment] 2019-05-16 16:10
We have an issue here with `wget`'s WARC format. They include the http response, which we didn't do with Creepy or when using the httrack to WARC converter (dir2warc). 

Python 3 `warc` library doesn't handle this well. It treats it as the payload (the HTML) but obviously it is not. We need to detect and ignore this header manually.

**Comment by lpla** [comment] 2019-05-16 16:43
Should be fixed with this commit. Also I merged changes to `bitextor-malign`

**Comment by lpla** [comment] 2019-05-17 13:27
Also, something I noticed today. Careful with `timeout` limits now with `wget`, because it kills the `wget` instance, which writes the WARC file now. If this happens, WARC could be partially written and not well formatted (it needs a double "\r\n" at the end of each document) and then, `bitextor-warc2preprocess.py` will crash.

**Comment by hieuhoang** [comment] 2019-05-17 14:00
Eek. Can't be careful when you've got 287000 hosts to crawl.

Does it have a time limit flag? Read the man page but nothing seems to fit.

Or replace time limit with something else. E.g. max number of pages

**Comment by hieuhoang** [comment] 2019-05-17 14:34
lets re-open this issue to carry on discussing a decent crawler.

**Comment by lpla** [comment] 2019-05-17 14:39
It has an optional time limit flag, as `httrack` and `creepy`. You can use it in all three by setting `crawlTimeLimit` in Bitextor config.

Also, you won't find it in `man` pages because we implement it using `timeout` command.

So, if you don't use this config option, you don't have to worry. I do, for testing purposes. That's why I posted my previous comment.

**Comment by hieuhoang** [comment] 2019-05-17 14:42
but if we use timeout with wget then some warcs will be corrupted. Which will cause loads of hassle for users and for you having to answer their questions. So we should disable it for wget and think of another way

**Comment by lpla** [comment] 2019-05-17 16:35
I think the best solution is implementing a check that, after wget is run/stopped, deletes the last WARC document if it is corrupted.

**Comment by hieuhoang** [comment] 2019-05-17 16:36
aye, something like that

**Closed** 2019-05-21 09:03 UTC
