### ISSUE TITLE
i get this message "line 590: [: too many arguments" when i try to crawl tutorials-point website

### ISSUE THREAD

**Issue by omarkaraksi** [bitextor/bitextor#3] opened 2018-05-07 09:53 UTC
when executed this command 
 ` bitextor -u https://www.tutorialspoint.com/numpy/numpy_advanced_indexing.htm -b 1 -v /home/omar/dict.bitextor -x en es `  

i got  `/usr/local/bin/bitextor: line 590: [: too many arguments
/usr/local/bin/bitextor: line 594: [: too many arguments
`
it takes too long time and then outputs empty TMX string.
is this problem with my installation ? or it is just a warning  ?

**Comment by Lesbinary** [comment] 2018-05-07 16:16
It is not a warning. I tried to reproduce the problem but the crawling is just massive for that website. Did you try with a smaller website? Take into account that Bitextor starts crawling at the base domain to find parallel documents, in this case, "tutorialspoint.com". So it ignores the full path of a specific page or part of the web ("numpy/numpy_advanced_indexing.htm" here).

Anyway, I cancelled the crawling after some minutes (just pressing Ctrl + C) and the process finished correctly without errors (with empty TMX), so I couldn't reproduce your problem. I don't know exactly why it shows you that error about arguments, I need more information to debug this problem. How did you install Bitextor? Does it happen with other websites? Are your dictionaries in the required format?

**Comment by omarkaraksi** [comment] 2018-05-08 04:26
I re-tested it with smaller web site  'f-g.com' same result empty TMX file , i used the installation guide in the repository. i don't know what do you mean by dictionaries in the required format ? 
Thanks in advance for your help.

**Comment by omarkaraksi** [comment] 2018-05-08 09:35
OK it worked fine with this website , but it failed with 'expedia.com' with this message 
"It was not possible to connect to the web server specified to retrieve the robots.txt file".
How can i bypass robots.txt .

**Comment by Lesbinary** [comment] 2018-05-08 10:38
Our crawler (Creepy) does not have an option to ignore robots.txt right now. It could be a feature or improvement in the future, but that is out of the topic of this issue. Please, if you want us to discuss and evaluate it, open a new issue requesting it and adding the tag "enhancement".

As a temporal workaround you could try another crawler which could ignore robots.txt and manually generate a ETT file from the crawl to run Bitextor from it with the option `--ett FILE`.

I will close this issue now as the main problems look solved.

**Closed by Lesbinary** 2018-05-08 10:38 UTC

**Comment by omarkaraksi** [comment] 2018-05-08 10:57
Thanks a lot for your effort.
