### ISSUE TITLE
Hunalign and Bicleaner errors

### ISSUE THREAD

**Issue by bjarnigithub** [bitextor/bitextor#234] opened 2022-04-27 13:43 UTC
Hi, 

I'm running Bitextor version 8.2 in a Conda environment (on Ubuntu in WSL) and I'm getting errors in connection with Hunalign and Bicleaner. If I set ftfy, cleanHTML, html5lib, boilerplateCleaning and paragraphIdentification to False, Bitextor encounters an error in "rule hunalign". But when I set them to True, there is no "rule hunalign" error, but Bitextor does crash on Bicleaner due to "bicleaner-ai-classify: error: argument -b/--block_size: expected one argument". I tried using both flavours of Bicleaner, i.e. AI and Classic, but it crashes on the same thing. Full error messages are displayed below. Does anyone know why this is happening and how I can fix this? 

Here is an error message for the Hunalign error. I got this when using warc2preprocess (Bitextor crashes on other lines in the code when using warc2text, but it was under "rule hunalign", and so far it has always been in the files bitextor/bitextor_align_segments.py and bitextor/docalign/bitextor_build_docalign.py): 

~~~
[Tue Apr 26 02:18:48 2022]
rule hunalign:
    input: data/transient/en_is/238/en1_is1.bitextor.06_01.matches, data/permanent/data/shards/en/238/1/sentences.gz, data/permanent/data/shards/is/238/1/sentences.gz, data/permanent/data/shards/en/238/1/url.gz, data/permanent/data/shards/is/238/1/url.gz, data/permanent/data/shards/en/238/1/tokenised.gz, data/permanent/data/shards/is/238/1/tokenised.>    output: data/transient/en_is/238/en1_is1.hunalign.06_02.segalign.gz
    jobid: 104
    wildcards: shard=238, src_batch=1, trg_batch=1
    resources: tmpdir=/tmp

Traceback (most recent call last):
  File "/home/user/.conda/envs/bitextor_v8-2/lib/python3.8/site-packages/bitextor/bitextor_align_segments.py", line 83, in align
    prev_hun = next(hunalign_output).strip()
StopIteration

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/user/.conda/envs/bitextor_v8-2/lib/python3.8/site-packages/bitextor/bitextor_align_segments.py", line 273, in <module>
    align(doc_id_1, doc_id_2, tmp_file1_name, tmp_file2_name, tmp_file1_orig_name, tmp_file2_orig_name,
  File "/home/user/.conda/envs/bitextor_v8-2/lib/python3.8/site-packages/bitextor/bitextor_align_segments.py", line 96, in align
    raise Exception("Could not get the documents for the first match: likely the provided files are not correct")
Exception: Could not get the documents for the first match: likely the provided files are not correct
Traceback (most recent call last):
  File "/home/user/.conda/envs/bitextor_v8-2/lib/python3.8/site-packages/bitextor/docalign/bitextor_build_docalign.py", line 122, in <module>
    sys.stdout.write(f"\t{d1}\t{d2}")
BrokenPipeError: [Errno 32] Broken pipe
[Tue Apr 26 02:18:51 2022]
Error in rule hunalign:
    jobid: 104
    output: data/transient/en_is/238/en1_is1.hunalign.06_02.segalign.gz
    shell:

        header="src_index       trg_index"

        python3 /home/user/.conda/envs/bitextor_v8-2/lib/python3.8/site-packages/bitextor/utils/cut_header.py -f src_index,trg_index --input data/transient/en_is/238/en1_is1.bitextor.06_01.matches             | tail -n +2             | LC_ALL=C sort -nk1,1 -t $'     '             | sed '1 s/^/'"$header"'\n/'             | python3 /home/user>

        (one of the commands exited with non-zero exit code; note that snakemake uses bash strict mode!)

Removing output files of failed job hunalign since they might be corrupted:
data/transient/en_is/238/en1_is1.hunalign.06_02.segalign.gz
Shutting down, this might take some time.
Exiting because a job execution failed. Look above for error message
The code used to generate one or several output files has changed:
    To inspect which output files have changes, run 'snakemake --list-code-changes'.
    To trigger a re-run, use 'snakemake -R $(snakemake --list-code-changes)'.
The input used to generate one or several output files has changed:
    To inspect which output files have changes, run 'snakemake --list-input-changes'.
    To trigger a re-run, use 'snakemake -R $(snakemake --list-input-changes)'.
~~~

Here is an error message for the Bicleaner error: 

~~~
[Tue Apr 26 18:05:05 2022]
rule bicleaner:
    input: data/transient/en_is/07_01.bifixer/0, data/bicleaner-model/bitextor_bicleaner_model/en-is/en-is.yaml
    output: data/transient/en_is/07_02.bicleaner/0.gz
    jobid: 89
    wildcards: batch=0
    threads: 2
    resources: tmpdir=/tmp

usage: bicleaner-ai-classify [-h] [-S SOURCE_TOKENIZER_COMMAND]
                             [-T TARGET_TOKENIZER_COMMAND] [--header]
                             [--scol SCOL] [--tcol TCOL] [-b BLOCK_SIZE]
                             [-p PROCESSES] [--batch_size BATCH_SIZE]
                             [--tmp_dir TMP_DIR] [-d DISCARDED_TUS]
                             [--score_only] [--calibrated] [--raw_output]
                             [--lm_threshold LM_THRESHOLD]
                             [--disable_hardrules] [--disable_lm_filter]
                             [--disable_porn_removal]
                             [--disable_minimal_length] [--run_all_rules]
                             [--rules_config RULES_CONFIG] [-q] [--debug]
                             [--logfile LOGFILE] [-v]
                             input [output] metadata
bicleaner-ai-classify: error: argument -b/--block_size: expected one argument
parallel: This job failed:
bicleaner-ai-classify -S /home/user/.conda/envs/bitextor_v8-2/lib/python3.8/site-packages/bitextor/data/moses/tokenizer/tokenizer.perl -q -b -a -l en -T /home/user/.conda/envs/bitextor_v8-2/lib/python3.8/site-packages/bitextor/data/moses/tokenizer/tokenizer.perl -q -b -a -l is --score_only --header -q - - data/bicleaner-model/bitextor_bicle>terminate called after throwing an instance of 'util::EndOfFileException'
  what():  End of file
/bin/bash: line 11: 1587594 Done                    $CAT data/transient/en_is/07_01.bifixer/0
     1587595 Aborted                 | cache -k $text_fields ${parallel_cmd} bicleaner-ai-classify -S "/home/user/.conda/envs/bitextor_v8-2/lib/python3.8/site-packages/bitextor/data/moses/tokenizer/tokenizer.perl -q -b -a -l en" -T "/home/user/.conda/envs/bitextor_v8-2/lib/python3.8/site-packages/bitextor/data/moses/tokenizer/tokenizer.perl>     1587596                       | paste <($CAT data/transient/en_is/07_01.bifixer/0) -
     1587597                       | pigz -c > data/transient/en_is/07_02.bicleaner/0.gz
[Tue Apr 26 18:05:09 2022]
Error in rule bicleaner:
    jobid: 89
    output: data/transient/en_is/07_02.bicleaner/0.gz
    shell:

        parallel_cmd=""
        if [ 2 -gt 1 ]; then
            parallel_cmd="parallel --gnu --halt 2 --pipe --j 2 -k"
        fi
        CAT=$([[ data/transient/en_is/07_01.bifixer/0 == *.gz ]] && echo "zcat" || echo "cat")
        slang=$(egrep "source_lang" data/bicleaner-model/bitextor_bicleaner_model/en-is/en-is.yaml | cut -d " " -f 2)
        text_fields=$(head -1 <($CAT data/transient/en_is/07_01.bifixer/0)             | python3 /home/user/.conda/envs/bitextor_v8-2/lib/python3.8/site-packages/bitextor/utils/cut_header.py -f src_text,trg_text --only-print-idxs             | tr -d '
')

        $CAT data/transient/en_is/07_01.bifixer/0             |  cache -k $text_fields ${parallel_cmd} bicleaner-ai-classify -S "/home/user/.conda/envs/bitextor_v8-2/lib/python3.8/site-packages/bitextor/data/moses/tokenizer/tokenizer.perl -q -b -a -l en" -T "/home/user/.conda/envs/bitextor_v8-2/lib/python3.8/site-packages/bitextor/data/mose>

        (one of the commands exited with non-zero exit code; note that snakemake uses bash strict mode!)

Removing output files of failed job bicleaner since they might be corrupted:
data/transient/en_is/07_02.bicleaner/0.gz
Shutting down, this might take some time.
Exiting because a job execution failed. Look above for error message
~~~

**Comment by cgr71ii** [comment] 2022-04-27 14:24
Hi!

Could you share the specific command that you ran in order to try to reproduce the problem (and the provided configuration file if used any)?

**Comment by bjarnigithub** [comment] 2022-04-28 23:40
Here is the command I used: 

~~~
bitextor-full --configfile yamls/config.yaml --cores 7
~~~

And here is the yaml file I used: 

~~~
# DATA FOLDERS
permanentDir: data/permanent/bitextor-output
dataDir: data/permanent/data
transientDir: data/transient
tempDir: data/transient

# WORKFLOW
parallelWorkers: {split: 2, tokenise: 2, docalign: 2, segalign: 2, bifixer: 2, bicleaner: 2, sents: 2} 

# DATA SOURCES
warcs: ["data/warcs/skatturinn.warc.gz"]

# PREPROCESSING
preprocessor: warc2preprocess
langID: cld3
ftfy: True
cleanHTML: True
html5lib: True
boilerplateCleaning: True 
paragraphIdentification: True 
parser: bs4

# SHARDING
shards: 8
batches: 3072

# LANGS
lang1: en
lang2: is

# DOCUMENT ALIGNMENT
documentAligner: DIC
dic: data/bilingLex/en-is_is-en_glossary_21-09/en-is.dic

# SEGMENT ALIGNMENT
sentenceAligner: hunalign 
sentenceAlignerThreshold: 0.1

# PARALLEL DATA FILTERING
bicleaner: True 
bicleanerModel: data/bicleaner-model/bitextor_bicleaner_model/en-is/en-is.yaml 
bicleanerFlavour: classic
bicleanerThreshold: 0.5

# POST-PROCESSING
bifixer: True
elrc: True
tmx: True
deduped: True
biroamer: False
~~~

**Comment by cgr71ii** [comment] 2022-05-02 10:15
The problem is fixed in master branch. The problem was related to the config value `parallelWorkers: {..., bicleaner: 2, ...}`. If you want to fix the problem in your conda installation instead of downloading and installing manually Bitextor, modifying `$CONDA_PREFIX/bitextor/bitextor/Snakefile` and applying the changes applied in commit https://github.com/bitextor/bitextor/commit/f0336755c236c2d052910c383926f772aa81f0a6, the problem should be gone (we will not release a new conda build for now).

Closing issue. Reopen if needed.

**Closed by cgr71ii** 2022-05-02 10:15 UTC
